const tabs=[];let active=-1;const $=s=>document.querySelector(s),content=$("#content"),tabsEl=$("#tabs"),address=$("#address");
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function normalize(v){v=String(v).trim();if(!v)return"untitled://newtab";if(/^(https?|file|untitled):\/\//i.test(v))return v;if(/^[a-z][a-z0-9+.-]*:\/\//i.test(v))return v;if(/^(?:[\w-]+\.)+[a-z]{2,}(?::\d+)?(?:[/?#].*)?$/i.test(v))return"https://"+v;return"https://www.google.com/search?q="+encodeURIComponent(v);}
function internalPage(type){const box=document.createElement("section");box.className="internal active";const s=window.__state||{history:[],bookmarks:[],downloads:[]};
if(type==="newtab")box.innerHTML='<div class="card"><h1>Untitled Browser</h1><p class="muted">Fast, private, yours.</p><div class="grid"><a class="link" href="https://www.google.com">Google</a><a class="link" href="https://www.youtube.com">YouTube</a><a class="link" href="https://github.com">GitHub</a><a class="link" href="https://www.roblox.com">Roblox</a></div></div>';
if(type==="settings")box.innerHTML='<div class="card"><h1>Settings</h1><p>Untitled Browser 1.0.0</p><h2>Privacy</h2><p class="muted">Remote pages never receive the browser shell preload. Chromium web security stays enabled.</p><h2>Shortcuts</h2><p>Ctrl+L address · Ctrl+T new tab · Ctrl+W close · Ctrl+R reload · Ctrl+Shift+I DevTools · Ctrl+D bookmark</p></div>';
if(type==="history")box.innerHTML='<div class="card"><h1>History</h1>'+s.history.map(x=>'<p><a class="link" href="'+esc(x.url)+'">'+esc(x.title||x.url)+'</a><br><small class="muted">'+new Date(x.time).toLocaleString()+'</small></p>').join("")+'</div>';
if(type==="bookmarks")box.innerHTML='<div class="card"><h1>Bookmarks</h1>'+s.bookmarks.map(x=>'<p><a class="link" href="'+esc(x.url)+'">'+esc(x.title||x.url)+'</a></p>').join("")+'</div>';
if(type==="downloads")box.innerHTML='<div class="card"><h1>Downloads</h1>'+s.downloads.map(x=>'<p>'+esc(x.name)+' — '+esc(x.status||"downloading")+'</p>').join("")+'</div>';
box.onclick=e=>{const a=e.target.closest("a");if(a){e.preventDefault();navigate(a.getAttribute("href"));}};return box;}
async function addTab(url="untitled://newtab"){const web=document.createElement("webview");web.className="webview";web.setAttribute("allowpopups","false");web.setAttribute("partition","persist:untitled");web.src=url;const id=tabs.length,t={id,url,title:"New Tab",web,internal:null};tabs.push(t);content.appendChild(web);["did-start-loading","did-navigate","did-navigate-in-page","page-title-updated"].forEach(e=>web.addEventListener(e,()=>update(t)));web.addEventListener("page-favicon-updated",e=>{t.favicon=e.favicons?.[0];renderTabs();});web.addEventListener("did-fail-load",e=>{if(e.errorCode!==-3)showError(t,e.errorCode,e.errorDescription||"Navigation failed");});activate(id);}
function activate(i){if(i<0||i>=tabs.length)return;active=i;tabs.forEach((t,n)=>{t.web.classList.toggle("active",n===i);t.internal?.classList.toggle("active",n===i);});updateChrome();renderTabs();}
function renderTabs(){tabsEl.innerHTML="";tabs.forEach((t,i)=>{const b=document.createElement("button");b.className="tab"+(i===active?" active":"");b.innerHTML=(t.favicon?'<img class="favicon" src="'+esc(t.favicon)+'">':'<span class="favicon"></span>')+'<span>'+esc(t.title||"New Tab")+'</span><span class="close">×</span>';b.onclick=e=>e.target.classList.contains("close")?closeTab(i):activate(i);tabsEl.appendChild(b);});}
function closeTab(i){tabs[i]?.web.remove();tabs[i]?.internal?.remove();tabs.splice(i,1);if(!tabs.length)addTab();else activate(Math.min(i,tabs.length-1));}
function update(t){if(active!==t.id)return;t.url=t.web.getURL()||t.url;t.title=t.web.getTitle()||t.title;updateChrome();renderTabs();if(t.url&&!/^untitled:/.test(t.url))window.untitled.addHistory({url:t.url,title:t.title});}
function updateChrome(){if(active<0)return;const t=tabs[active];address.value=t.url.startsWith("untitled://")?"":t.url;window.untitled.isBookmarked(t.url).then(v=>$("#bookmark").textContent=v?"★":"☆");}
function navigate(raw){const u=normalize(raw),t=tabs[active];if(!t)return;if(t.internal){t.internal.remove();t.internal=null;t.web.style.display="flex";}t.web.loadURL(u);}
function showInternal(type){const t=tabs[active];if(!t)return;t.web.style.display="none";t.internal?.remove();t.internal=internalPage(type);content.appendChild(t.internal);t.url="untitled://"+type;t.title=type==="newtab"?"New Tab":type[0].toUpperCase()+type.slice(1);activate(active);}
function showError(t,code,msg){t.web.style.display="none";t.internal?.remove();const box=document.createElement("section");box.className="internal active";box.innerHTML='<div class="card"><h1>Page unavailable</h1><p class="muted">Error '+esc(code)+' — '+esc(msg)+'</p><button id="retry">Retry</button> <button id="homeError">New Tab</button></div>';box.querySelector("#retry").onclick=()=>navigate(t.url);box.querySelector("#homeError").onclick=()=>showInternal("newtab");t.internal=box;content.appendChild(box);}
document.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{const t=tabs[active];if(!t)return;b.dataset.action==="back"?t.web.goBack():b.dataset.action==="forward"?t.web.goForward():t.web.reload();});
$("#newTab").onclick=()=>addTab();$("#home").onclick=()=>showInternal("newtab");$("#menu").onclick=()=>$("#menuPanel").hidden=!$("#menuPanel").hidden;$("#devtools").onclick=()=>window.untitled.openDevTools();$("#menuPanel").onclick=e=>{const p=e.target.dataset.page;if(p){$("#menuPanel").hidden=true;showInternal(p);}};
$("#bookmark").onclick=async()=>{const t=tabs[active];if(t&&!t.url.startsWith("untitled://")){await window.untitled.toggleBookmark({url:t.url,title:t.title});updateChrome();}};
address.onkeydown=e=>{if(e.key==="Enter")navigate(address.value);};
window.onkeydown=e=>{const m=e.ctrlKey||e.metaKey;if(m&&e.key.toLowerCase()==="l"){e.preventDefault();address.focus();address.select();}else if(m&&e.key.toLowerCase()==="t"){e.preventDefault();addTab();}else if(m&&e.key.toLowerCase()==="w"){e.preventDefault();closeTab(active);}else if(m&&e.key.toLowerCase()==="r"){e.preventDefault();tabs[active]?.web.reload();}else if(m&&e.shiftKey&&e.key.toLowerCase()==="i"){e.preventDefault();window.untitled.openDevTools();}else if(m&&e.key.toLowerCase()==="d"){e.preventDefault();$("#bookmark").click();}else if(e.altKey&&e.key==="ArrowLeft")tabs[active]?.web.goBack();else if(e.altKey&&e.key==="ArrowRight")tabs[active]?.web.goForward();};
window.untitled.onOpenUrl(u=>navigate(u));(async()=>{window.__state=await window.untitled.getState();await addTab();})();
