(() => {
  const dictionaries = {
    en: {
      newTab:'New Tab', search:'Search or enter address', back:'Back', forward:'Forward', reload:'Reload', home:'Home', bookmark:'Bookmark', menu:'Menu',
      history:'History', downloads:'Downloads', bookmarks:'Bookmarks', extensions:'Extensions', settings:'Settings', privacy:'Privacy', performance:'Performance', security:'Security', about:'About', shortcuts:'Shortcuts', taskManager:'Task manager',
      quickLinks:'Quick links', session:'Session', searchTitle:'Search', go:'Go', openNewTab:'Open new tab', noHistory:'No history entries.', noDownloads:'No downloads yet.', noBookmarks:'No bookmarks yet. Press Ctrl+D on a page.',
      language:'Language', background:'New Tab background', chooseBackground:'Choose image', clearBackground:'Remove background', save:'Save settings', saved:'Saved', homePage:'Home page', searchEngine:'Search engine', askDownloads:'Ask where to save downloads',
      discord:'Discord Rich Presence', enableRpc:'Enable Discord RPC', appId:'Application ID', showTitle:'Show page/video title', showSite:'Show current domain', showSearch:'Show current search query', showPageButton:'Add Open page button', testConnection:'Test Connection',
      securitySettings:'Security & networking', httpsOnly:'HTTPS-only mode', httpsOnlyHelp:'Upgrade normal HTTP navigations to HTTPS except localhost.', dns:'DNS', dnsMode:'Secure DNS mode', dnsServers:'DNS-over-HTTPS servers', proxy:'Proxy', proxyEnabled:'Enable proxy', proxyMode:'Routing mode', proxyScheme:'Scheme', proxyHost:'Host', proxyPort:'Port', proxyUser:'Username', proxyPassword:'Password', proxyDomains:'Split tunnel domains', proxyBypass:'Proxy bypass rules', direct:'Direct', all:'All traffic', split:'Split tunneling',
      securityApply:'Apply security settings', securityNote:'Permissions are denied by default. Remote pages do not receive the browser preload bridge.', incognito:'New private tab', screenshot:'Screenshot', pip:'Picture-in-Picture', alwaysOnTop:'Always on top', zoomOut:'Zoom out', zoomIn:'Zoom in', zoomReset:'Reset zoom', devtools:'Developer tools', menuTitle:'Menu', newTabAction:'New tab',
      browsing:'Browsing the web', private:'Private browsing', watching:'Watching', listening:'Listening'
    },
    ru: {
      newTab:'Новая вкладка', search:'Поиск или адрес', back:'Назад', forward:'Вперёд', reload:'Обновить', home:'Домой', bookmark:'Закладка', menu:'Меню',
      history:'История', downloads:'Загрузки', bookmarks:'Закладки', extensions:'Расширения', settings:'Настройки', privacy:'Приватность', performance:'Производительность', security:'Безопасность', about:'О браузере', shortcuts:'Горячие клавиши', taskManager:'Диспетчер задач',
      quickLinks:'Быстрые ссылки', session:'Сессия', searchTitle:'Поиск', go:'Открыть', openNewTab:'Новая вкладка', noHistory:'История пуста.', noDownloads:'Загрузок пока нет.', noBookmarks:'Закладок пока нет. Нажми Ctrl+D на странице.',
      language:'Язык', background:'Фон новой вкладки', chooseBackground:'Выбрать изображение', clearBackground:'Убрать фон', save:'Сохранить настройки', saved:'Сохранено', homePage:'Домашняя страница', searchEngine:'Поисковая система', askDownloads:'Спрашивать, куда сохранять загрузки',
      discord:'Discord Rich Presence', enableRpc:'Включить Discord RPC', appId:'Application ID', showTitle:'Показывать название страницы/видео', showSite:'Показывать домен', showSearch:'Показывать поисковый запрос', showPageButton:'Добавлять кнопку Open page', testConnection:'Проверить соединение',
      securitySettings:'Безопасность и сеть', httpsOnly:'Только HTTPS', httpsOnlyHelp:'Переводить обычный HTTP на HTTPS, кроме localhost.', dns:'DNS', dnsMode:'Режим защищённого DNS', dnsServers:'DNS-over-HTTPS серверы', proxy:'Прокси', proxyEnabled:'Включить прокси', proxyMode:'Режим маршрутизации', proxyScheme:'Схема', proxyHost:'Хост', proxyPort:'Порт', proxyUser:'Логин', proxyPassword:'Пароль', proxyDomains:'Домены для раздельного туннеля', proxyBypass:'Правила обхода прокси', direct:'Напрямую', all:'Весь трафик', split:'Раздельное туннелирование',
      securityApply:'Применить настройки безопасности', securityNote:'Разрешения запрещены по умолчанию. Удалённые сайты не получают preload браузера.', incognito:'Новая приватная вкладка', screenshot:'Скриншот', pip:'Картинка в картинке', alwaysOnTop:'Поверх всех окон', zoomOut:'Уменьшить масштаб', zoomIn:'Увеличить масштаб', zoomReset:'Сбросить масштаб', devtools:'Инструменты разработчика', menuTitle:'Меню', newTabAction:'Новая вкладка',
      browsing:'Просматривает интернет', private:'Приватный просмотр', watching:'Смотрит', listening:'Слушает'
    },
    de: { language:'Sprache', taskManager:'Task-Manager', incognito:'Privater Tab', screenshot:'Screenshot', pip:'Bild-in-Bild', alwaysOnTop:'Immer im Vordergrund', zoomOut:'Verkleinern', zoomIn:'Vergrößern', zoomReset:'Zoom zurücksetzen', devtools:'Entwicklertools', menuTitle:'Menü', newTabAction:'Neuer Tab', newTab:'Neuer Tab', settings:'Einstellungen', security:'Sicherheit', background:'Neuer-Tab-Hintergrund', chooseBackground:'Bild auswählen', clearBackground:'Hintergrund entfernen', save:'Speichern', securitySettings:'Sicherheit & Netzwerk', httpsOnly:'Nur HTTPS', proxy:'Proxy' },
    es: { language:'Idioma', taskManager:'Administrador de tareas', incognito:'Pestaña privada', screenshot:'Captura', pip:'Imagen en imagen', alwaysOnTop:'Immer im Vordergrund', zoomOut:'Alejar', zoomIn:'Acercar', zoomReset:'Restablecer zoom', devtools:'Herramientas de desarrollo', menuTitle:'Menú', newTabAction:'Nueva pestaña', newTab:'Nueva pestaña', settings:'Configuración', security:'Seguridad', background:'Fondo de nueva pestaña', chooseBackground:'Elegir imagen', clearBackground:'Quitar fondo', save:'Guardar', securitySettings:'Seguridad y red', httpsOnly:'Solo HTTPS', proxy:'Proxy' },
    uk: { language:'Мова', taskManager:'Диспетчер завдань', incognito:'Нова приватна вкладка', screenshot:'Знімок екрана', pip:'Картинка в картинці', alwaysOnTop:'Поверх усіх вікон', zoomOut:'Зменшити масштаб', zoomIn:'Збільшити масштаб', zoomReset:'Скинути масштаб', devtools:'Інструменти розробника', menuTitle:'Меню', newTabAction:'Нова вкладка', newTab:'Нова вкладка', settings:'Налаштування', security:'Безпека', background:'Фон нової вкладки', chooseBackground:'Вибрати зображення', clearBackground:'Прибрати фон', save:'Зберегти', securitySettings:'Безпека та мережа', httpsOnly:'Лише HTTPS', proxy:'Проксі' }
  };
  let current = localStorage.getItem('untitled-language') || 'en';
  function t(key){ return dictionaries[current]?.[key] || dictionaries.en[key] || key; }
  function apply(){ document.documentElement.lang=current; document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n)); document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder)); document.querySelectorAll('[data-i18n-title]').forEach(el=>el.title=t(el.dataset.i18nTitle)); }
  async function setLanguage(lang){ current=dictionaries[lang]?lang:'en'; localStorage.setItem('untitled-language',current); apply(); window.dispatchEvent(new CustomEvent('untitled-language-change',{detail:current})); return current; }
  window.untitledI18n={t,setLanguage,getLanguage:()=>current,apply,languages:Object.keys(dictionaries)};
  window.addEventListener('DOMContentLoaded',apply);
})();
