(() => {
  const panel = document.getElementById('internalPanel');
  let current = { route: null, params: {} };
  const $ = (s, root = panel) => root.querySelector(s);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const t = k => window.untitledI18n?.t(k) || k;
  const card = (title, body) => `<section class="internal-card"><h2>${esc(title)}</h2>${body}</section>`;
  const btn = (label, attrs='') => `<button class="internal-button" ${attrs}>${esc(label)}</button>`;
  function show(){panel.classList.remove('hidden')}
  function hide(){panel.classList.add('hidden')}
  function navigate(route, params={}){return window.untitled.tabs.internal(route, params)}
  function header(title, sub=''){return `<div class="internal-header"><div><div class="internal-eyebrow">untitled://</div><h1>${esc(title)}</h1>${sub?`<p class="internal-muted">${esc(sub)}</p>`:''}</div><div class="internal-brand">UNTITLED BROWSER</div></div>`}
  function wireCommon(){panel.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));panel.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>window.untitled.tabs.action('back'))}
  async function renderNewtab(){
    const s=await window.untitled.settings.get(); if(s.language) await window.untitledI18n?.setLanguage(s.language);
    const bg=s.homeBackgroundUrl||'';
    panel.innerHTML=`<section class="newtab-hero" style="background-image:${bg?`url('${esc(bg)}')`:'none'}"><div class="newtab-content"><div class="internal-eyebrow">UNTITLED://NEW_TAB</div><h1>${esc(t('newTab'))}</h1><div class="newtab-clock" id="newtabClock"></div><div class="internal-grid">${card(t('quickLinks'),`<div class="quick-grid">${['history','downloads','bookmarks','extensions','settings','security','privacy','performance'].map(r=>btn(t(r),`data-route="${r}"`)).join('')}</div>`)}${card(t('searchTitle'),`<div class="search-line"><input id="internalSearch" class="internal-input" data-i18n-placeholder="search" placeholder="${esc(t('search'))}" autofocus>${btn(t('go'),'id="goSearch"')}</div>`)}${card(t('session'),`<div class="quick-grid">${btn(t('openNewTab'),'data-route="newtab"')}${btn(t('shortcuts'),'data-route="shortcuts"')}${btn(t('about'),'data-route="about"')}</div>`)}</div></div></section>`;
    const searchInput=$('#internalSearch'); const searchBox=document.createElement('div'); searchBox.className='internal-suggestions'; searchInput.parentElement.style.position='relative'; searchInput.parentElement.appendChild(searchBox); let suggestionTimer;
    const hideSuggestions=()=>{searchBox.classList.remove('visible');searchBox.innerHTML='';};
    const showSuggestions=items=>{if(!items.length){hideSuggestions();return;}searchBox.innerHTML=items.map((x,i)=>`<button type="button" class="internal-suggestion" data-index="${i}">⌕ <span>${esc(x)}</span></button>`).join('');searchBox.querySelectorAll('button').forEach(b=>b.onmousedown=e=>{e.preventDefault();searchInput.value=items[Number(b.dataset.index)];hideSuggestions();window.untitled.tabs.navigate(searchInput.value)});searchBox.classList.add('visible');};
    searchInput.oninput=()=>{clearTimeout(suggestionTimer);suggestionTimer=setTimeout(async()=>{const q=searchInput.value.trim();if(!q||q.includes('://'))return hideSuggestions();const items=await window.untitled.search.suggestions(q,s.searchEngine);showSuggestions(items)},130)};
    searchInput.onblur=()=>setTimeout(hideSuggestions,120); searchInput.onkeydown=e=>{if(e.key==='Escape')hideSuggestions();if(e.key==='Enter'){hideSuggestions();window.untitled.tabs.navigate(searchInput.value)}}; $('#goSearch').onclick=()=>{hideSuggestions();window.untitled.tabs.navigate(searchInput.value)};const tick=()=>{const d=new Date();const el=$('#newtabClock');if(el)el.textContent=d.toLocaleString()};tick();clearInterval(renderNewtab.timer);renderNewtab.timer=setInterval(tick,1000);wireCommon();
  }
  async function renderHistory(){const items=await window.untitled.history.get();panel.innerHTML=`${header(t('history'),`${items.length} saved entries`)}<div class="internal-toolbar">${btn(t('back'),'data-back')}${btn('Clear all','id="clearHistory" class="danger"')}<input id="historySearch" class="internal-input small-input" placeholder="Search history"></div><div id="historyList" class="internal-list"></div>`;const list=$('#historyList');const draw=f=>{const q=f.trim().toLowerCase();const rows=items.filter(h=>!q||`${h.title} ${h.url}`.toLowerCase().includes(q));list.innerHTML=rows.length?rows.map(h=>`<div class="internal-item"><div class="internal-main"><div class="internal-title">${esc(h.title||h.url)}</div><div class="internal-url">${esc(h.url)}</div></div><span class="internal-badge">${esc(new Date(h.time).toLocaleString())}</span><button class="internal-button" data-open="${esc(h.url)}">Open</button></div>`).join(''):`<div class="empty-state">${esc(t('noHistory'))}</div>`;list.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>window.untitled.tabs.navigate(b.dataset.open))};draw('');$('#historySearch').oninput=e=>draw(e.target.value);$('#clearHistory').onclick=async()=>{await window.untitled.history.clear();renderHistory()};wireCommon()}
  async function renderDownloads(){const items=await window.untitled.downloads.get();panel.innerHTML=`${header(t('downloads'),`${items.length} recorded downloads`)}<div class="internal-toolbar">${btn(t('back'),'data-back')}</div><div id="downloadList" class="internal-list"></div>`;const list=$('#downloadList');list.innerHTML=items.length?items.map(d=>`<div class="internal-item"><div class="internal-main"><div class="internal-title">${esc(d.filename)}</div><div class="internal-url">${esc(d.path||d.url||'')}</div><div class="internal-progress"><span style="width:${d.total>0?Math.min(100,(d.received/d.total)*100):0}%"></span></div></div><span class="internal-badge">${esc(d.state)}</span>${d.path?`<button class="internal-button" data-show="${esc(d.path)}">Folder</button><button class="internal-button" data-open="${esc(d.path)}">Open</button>`:''}</div>`).join(''):`<div class="empty-state">${esc(t('noDownloads'))}</div>`;list.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>window.untitled.downloads.show(b.dataset.show));list.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>window.untitled.downloads.open(b.dataset.open));wireCommon()}
  async function renderBookmarks(){const items=await window.untitled.bookmarks.get();panel.innerHTML=`${header(t('bookmarks'),`${items.length} saved bookmarks`)}<div class="internal-toolbar">${btn(t('back'),'data-back')}</div><div id="bookmarkList" class="internal-list"></div>`;const list=$('#bookmarkList');list.innerHTML=items.length?items.map(b=>`<div class="internal-item"><div class="internal-main"><div class="internal-title">${esc(b.title)}</div><div class="internal-url">${esc(b.url)}</div></div>${btn('Open',`data-open="${esc(b.url)}"`)}${btn('Delete',`data-delete="${esc(b.id)}" class="danger"`)}</div>`).join(''):`<div class="empty-state">${esc(t('noBookmarks'))}</div>`;list.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>window.untitled.tabs.navigate(b.dataset.open));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{await window.untitled.bookmarks.delete(b.dataset.delete);renderBookmarks()});wireCommon()}
  async function renderExtensions(){let items=[];try{items=await window.untitled.extensions.list()}catch(_){ }panel.innerHTML=`${header(t('extensions'),'Chromium-compatible unpacked extensions.')}<div class="internal-toolbar">${btn(t('back'),'data-back')}${btn('Load unpacked','id="loadExt"')}</div><div class="internal-list">${items.length?items.map(e=>`<div class="internal-item"><div class="internal-main"><div class="internal-title">${esc(e.name)} <span class="internal-badge">${esc(e.version)}</span></div><div class="internal-url">${esc(e.id)}</div></div>${btn('Remove',`data-remove="${esc(e.id)}" class="danger"`)}</div>`).join(''):`<div class="empty-state">No extensions installed.</div>`}</div>`;$('#loadExt').onclick=async()=>{const p=prompt('Full path to an unpacked extension folder:');if(!p)return;try{await window.untitled.extensions.load(p);renderExtensions()}catch(e){alert(e.message)}};panel.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{await window.untitled.extensions.remove(b.dataset.remove);renderExtensions()});wireCommon()}
  async function renderSettings(){
    const s=await window.untitled.settings.get(); if(s.language) await window.untitledI18n?.setLanguage(s.language); const sec=s.security||{}; const px=sec.proxy||{}; const dns=sec.dns||{};
    panel.innerHTML=`${header(t('settings'),'Changes are stored locally.')}<div class="internal-grid">
      ${card(t('language'),`<label class="field">${esc(t('language'))}<select id="language" class="internal-input"><option value="ru">Русский</option><option value="en">English</option><option value="uk">Українська</option><option value="de">Deutsch</option><option value="es">Español</option></select></label>`)}</div>
      <div class="internal-grid">
      ${card('General',`<label class="field">${esc(t('homePage'))}<input id="home" class="internal-input" value="${esc(s.homePage||'')}"></label><label class="field">${esc(t('searchEngine'))}<select id="searchEngine" class="internal-input"><option value="https://duckduckgo.com/?q=">DuckDuckGo</option><option value="https://www.google.com/search?q=">Google</option><option value="https://www.bing.com/search?q=">Bing</option><option value="https://search.brave.com/search?q=">Brave Search</option><option value="https://www.startpage.com/sp/search?query=">Startpage</option></select></label><label class="field">Download folder<input id="downloadFolder" class="internal-input" value="${esc(s.downloadFolder||'')}" readonly></label><div class="button-row">${btn('Choose folder','id="chooseDownloadFolder" class="primary"')}</div><label class="check"><input type="checkbox" id="askDownloads" ${s.askDownloadLocation?'checked':''}> ${esc(t('askDownloads'))}</label><label class="check"><input type="checkbox" id="restoreSession" ${s.restoreSession!==false?'checked':''}> Restore previous session on startup</label><label class="check"><input type="checkbox" id="hardwareAcceleration" ${s.hardwareAcceleration!==false?'checked':''}> Hardware acceleration <span class="internal-muted">(restart required)</span></label>`)}
      ${card(t('background'),`<div class="background-preview" id="bgPreview" style="background-image:${s.homeBackgroundUrl?`url('${esc(s.homeBackgroundUrl)}')`:'none'}"></div><div class="button-row" style="margin-top:10px">${btn(t('chooseBackground'),'id="chooseBg" class="primary"')}${btn(t('clearBackground'),'id="clearBg"')}</div>`)}</div>
      <div class="internal-grid">${card('Privacy',`<label class="check"><input type="checkbox" id="dnt" ${s.doNotTrack?'checked':''}> Do Not Track</label><label class="check"><input type="checkbox" id="clearExit" ${s.clearDataOnExit?'checked':''}> Clear data on exit</label>${btn('Clear browsing data','id="clearData" class="danger"')}`)}
      <div class="internal-grid">${card(t('discord'),`<label class="check"><input type="checkbox" id="rpcEnabled" ${s.discord?.enabled?'checked':''}> ${esc(t('enableRpc'))}</label><div class="internal-item"><div class="internal-main"><div class="internal-title">Fixed Discord Application</div><div class="internal-url">1555622761924272249</div></div></div><label class="field">Details<input id="rpcDetails" class="internal-input" value="${esc(s.discord?.details||'Browsing the web')}"></label><label class="check"><input type="checkbox" id="rpcTitle" ${s.discord?.showTitle!==false?'checked':''}> ${esc(t('showTitle'))}</label><label class="check"><input type="checkbox" id="rpcSite" ${s.discord?.showSite!==false?'checked':''}> ${esc(t('showSite'))}</label><label class="check"><input type="checkbox" id="rpcSearch" ${s.discord?.showSearch!==false?'checked':''}> ${esc(t('showSearch'))}</label><div class="button-row">${btn(t('testConnection'),'id="rpcTest"')}<span id="rpcStatus" class="internal-muted"></span></div>`)}</div>
      <div class="internal-grid">${card(t('securitySettings'),`<label class="check"><input type="checkbox" id="httpsOnly" ${sec.httpsOnly?'checked':''}> ${esc(t('httpsOnly'))}</label><p class="internal-muted">${esc(t('httpsOnlyHelp'))}</p><label class="field">${esc(t('dnsMode'))}<select id="dnsMode" class="internal-input"><option value="automatic">Automatic</option><option value="secure">Secure DNS (DoH)</option><option value="off">Off</option></select></label><label class="field">${esc(t('dnsServers'))}<textarea id="dnsServers" class="internal-input" rows="3">${esc((dns.servers||[]).join('\n'))}</textarea></label><label class="check"><input type="checkbox" id="proxyEnabled" ${px.enabled?'checked':''}> ${esc(t('proxyEnabled'))}</label><label class="field">${esc(t('proxyMode'))}<select id="proxyMode" class="internal-input"><option value="direct">${esc(t('direct'))}</option><option value="all">${esc(t('all'))}</option><option value="split">${esc(t('split'))}</option></select></label><label class="field">${esc(t('proxyScheme'))}<select id="proxyScheme" class="internal-input"><option>http</option><option>https</option><option>socks4</option><option>socks5</option></select></label><label class="field">${esc(t('proxyHost'))}<input id="proxyHost" class="internal-input" value="${esc(px.host||'')}"></label><label class="field">${esc(t('proxyPort'))}<input id="proxyPort" class="internal-input" value="${esc(px.port||'')}"></label><div class="security-grid"><label class="field">${esc(t('proxyUser'))}<input id="proxyUser" class="internal-input" value="${esc(px.username||'')}"></label><label class="field">${esc(t('proxyPassword'))}<input id="proxyPassword" type="password" class="internal-input" value="${esc(px.password||'')}"></label></div><label class="field">${esc(t('proxyDomains'))}<textarea id="proxyDomains" class="internal-input" rows="3">${esc(px.domains||'')}</textarea></label><label class="field">${esc(t('proxyBypass'))}<input id="proxyBypass" class="internal-input" value="${esc(px.bypass||'')}"></label><p class="internal-muted">${esc(t('securityNote'))}</p><div class="button-row">${btn(t('securityApply'),'id="applySecurity" class="primary"')}<span id="securitySaved" class="internal-muted"></span></div>`)}</div>
      <div class="internal-grid">${card('Advanced',`<label class="field">Custom User-Agent<input id="ua" class="internal-input" value="${esc(s.userAgent?.custom||'')}"></label><div class="button-row">${btn(t('save'),'id="saveSettings" class="primary"')}<span id="saved" class="internal-muted"></span></div>`)}</div>`;
    $('#language').value=s.language||'en';$('#searchEngine').value=s.searchEngine;$('#dnsMode').value=dns.mode||'automatic';$('#proxyMode').value=px.mode||'direct';$('#proxyScheme').value=px.scheme||'http';
    $('#language').onchange=async()=>{await window.untitled.settings.set({language:$('#language').value});await window.untitledI18n.setLanguage($('#language').value);renderSettings()};
    $('#chooseBg').onclick=async()=>{try{await window.untitled.settings.chooseBackground();renderSettings()}catch(e){alert(e.message)}};$('#clearBg').onclick=async()=>{await window.untitled.settings.clearBackground();renderSettings()};$('#chooseDownloadFolder').onclick=async()=>{try{await window.untitled.settings.chooseDownloadFolder();renderSettings()}catch(e){alert(e.message)}};
    $('#applySecurity').onclick=async()=>{const security={httpsOnly:$('#httpsOnly').checked,dns:{mode:$('#dnsMode').value,servers:$('#dnsServers').value.split(/\n+/).map(x=>x.trim()).filter(Boolean)},proxy:{enabled:$('#proxyEnabled').checked,mode:$('#proxyMode').value,scheme:$('#proxyScheme').value,host:$('#proxyHost').value.trim(),port:$('#proxyPort').value.trim(),username:$('#proxyUser').value, password:$('#proxyPassword').value, domains:$('#proxyDomains').value,bypass:$('#proxyBypass').value}};try{await window.untitled.settings.set({security});$('#securitySaved').textContent=t('saved');setTimeout(()=>$('#securitySaved').textContent='',1600)}catch(e){alert(e.message)}};
    $('#rpcTest').onclick=async()=>{const r=await window.untitled.discord.test();$('#rpcStatus').textContent=r.ok?'● Connected':`● ${r.error||'Error'}`};
    $('#saveSettings').onclick=async()=>{const next={language:$('#language').value,homePage:$('#home').value.trim()||'untitled://newtab',searchEngine:$('#searchEngine').value,askDownloadLocation:$('#askDownloads').checked,restoreSession:$('#restoreSession').checked,hardwareAcceleration:$('#hardwareAcceleration').checked,doNotTrack:$('#dnt').checked,clearDataOnExit:$('#clearExit').checked,discord:{enabled:$('#rpcEnabled').checked,applicationId:'1555622761924272249',details:$('#rpcDetails').value,showSite:$('#rpcSite').checked,showSearch:$('#rpcSearch').checked,showTitle:$('#rpcTitle').checked,showPageButton:$('#rpcPageButton').checked},userAgent:{...s.userAgent,mode:$('#ua').value.trim()?'custom':'default',custom:$('#ua').value.trim()}};await window.untitled.settings.set(next);await window.untitledI18n.setLanguage(next.language);$('#saved').textContent=t('saved');setTimeout(()=>$('#saved').textContent='',1400)};
    $('#clearData').onclick=async()=>{await window.untitled.privacy.clear({});alert('Browsing data cleared.')};
  }
  async function renderSecurity(){return renderSettings()}
  async function renderPrivacy(){panel.innerHTML=`${header(t('privacy'),'Local privacy controls and data clearing.')}<div class="internal-grid">${card('Stored data',`<p class="internal-muted">History, bookmarks and download records stay in the local browser profile.</p>${btn('Clear browsing data','id="clearPrivacy" class="danger"')}`)}${card('Notice',`<p class="internal-muted">Privacy settings reduce local tracking exposure but do not make you anonymous on the Internet.</p>`)}</div>`;$('#clearPrivacy').onclick=async()=>{await window.untitled.privacy.clear({});alert('Browsing data cleared.')};wireCommon()}
  async function renderPerformance(){const m=await window.untitled.metrics.get();const ram=m.reduce((a,x)=>a+Number(x.memory?.workingSetSize||0),0);panel.innerHTML=`${header(t('performance'),'Chromium/Electron process snapshot.')}<div class="stat-grid">${card('Processes',`<div class="big-stat">${m.length}</div>`)}${card('RAM',`<div class="big-stat">${Math.round(ram/1024)} MB</div>`)}</div><div class="internal-list">${m.map(x=>`<div class="internal-item"><div class="internal-main"><div class="internal-title">${esc(x.name||x.type)}</div><div class="internal-url">PID ${esc(x.pid)} · ${esc(x.type||'process')}</div></div><span class="internal-badge">CPU ${Number(x.cpu?.percent||0).toFixed(1)}%</span><span class="internal-badge">RAM ${Math.round(Number(x.memory?.workingSetSize||0)/1024)} MB</span></div>`).join('')}</div>`;wireCommon()}
  async function renderTaskManager(){return renderPerformance()}
  async function renderShortcuts(){panel.innerHTML=`${header(t('shortcuts'),'Shortcuts handled in the Electron main process.')}<div class="internal-list">${[['Ctrl+L','Focus address bar'],['Ctrl+T','New tab'],['Ctrl+W','Close tab'],['Ctrl+Shift+T','Restore closed tab'],['Ctrl+Shift+N','Private tab'],['Ctrl+Tab / Ctrl+Shift+Tab','Switch tabs'],['Ctrl+1..9','Select tab'],['Ctrl+H','History'],['Ctrl+J','Downloads'],['Ctrl+D','Bookmark'],['Ctrl+Shift+B','Bookmarks'],['Ctrl+Shift+I / F12','Developer tools'],['Alt+Left / Right','Back / Forward'],['Ctrl+Shift+S','Screenshot'],['Ctrl+S','Save page'],['Ctrl+P','Print page'],['Ctrl+Shift+Del','Clear site data'],['Ctrl+Plus / Minus / 0','Zoom']].map(x=>`<div class="internal-item"><span class="mono">${esc(x[0])}</span><span class="internal-muted">${esc(x[1])}</span></div>`).join('')}</div>`;wireCommon()}
  async function renderAbout(){const v=await window.untitled.app.version();panel.innerHTML=`${header(t('about'),'Small open-source Chromium browser shell.')}<div class="internal-grid">${card('Versions',`<div class="version-grid"><span>App</span><span>${esc(v.app)}</span><span>Electron</span><span>${esc(v.electron)}</span><span>Chromium</span><span>${esc(v.chromium)}</span><span>Node</span><span>${esc(v.node)}</span></div>`)}${card('Matoi easter egg',`<p class="internal-muted">The attached artwork is used locally on custom error pages.</p>${btn('Show 403 error','id="showError"')}`)}</div>`;$('#showError').onclick=()=>navigate('error',{code:'403',url:'about:untitled'});wireCommon()}
  async function renderError(){const p=current.params||{};const code=esc(p.code||'ERR_FAILED');const friendly={'403':'ACCESS DENIED','404':'PAGE NOT FOUND','500':'SERVER ERROR','502':'BAD GATEWAY','503':'SERVICE UNAVAILABLE','504':'GATEWAY TIMEOUT'}[p.code]||'CONNECTION ERROR';panel.innerHTML=`<section class="error-page"><div class="error-photo-wrap"><img class="error-photo" src="../../assets/matoi/error-main.png" alt="Matoi error illustration"><div class="sheet-overlay"><div class="sheet-code">${code}</div><div class="sheet-label">${esc(friendly)}</div></div></div><div class="error-side"><div class="internal-eyebrow">UNTITLED://ERROR</div><h1>${code}</h1><div class="error-title">${esc(friendly)}</div><p class="internal-muted">${p.code?.startsWith('ERR_')?esc(p.message||'The page could not be loaded.'):'The page returned an HTTP error. You can retry it, go back, or open a fresh tab.'}</p><div class="button-row">${btn('Back','id="errBack"')}${btn('Retry','id="errRetry"')}${btn('New tab','id="errNew" class="primary"')}</div><div class="small">${esc(p.url||'')}</div></div></section>`;$('#errBack').onclick=()=>window.untitled.tabs.action('error-back');$('#errRetry').onclick=()=>window.untitled.tabs.action('error-retry');$('#errNew').onclick=()=>window.untitled.tabs.action('error-new-tab')}
  async function render(route,params){current={route,params:params||{}};show();panel.classList.toggle('error-host',route==='error');try{switch(route){case'newtab':return renderNewtab();case'history':return renderHistory();case'downloads':return renderDownloads();case'bookmarks':return renderBookmarks();case'extensions':return renderExtensions();case'settings':return renderSettings();case'security':return renderSettings();case'about':return renderAbout();case'privacy':return renderPrivacy();case'performance':return renderPerformance();case'task-manager':return renderTaskManager();case'shortcuts':return renderShortcuts();case'error':return renderError();default:return renderNewtab()}}catch(e){panel.innerHTML=`${header('Internal page error','The browser caught an error while rendering this page.')}<div class="internal-card"><p class="internal-muted">${esc(e?.message||e)}</p>${btn('Back','data-back')}</div>`;wireCommon()}}
  window.untitledInternal={render,hide};window.untitledI18n?.apply();
})();
