const app = document.getElementById('app');
const routeRaw = location.hash.replace(/^#/,'') || 'newtab';
const [route, query=''] = routeRaw.split('?');
const params = new URLSearchParams(query);
const esc = s => String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const card = (title, body) => `<section class="card"><h2>${title}</h2>${body}</section>`;
function shell(title, body){app.innerHTML=`<div class="top"><div><div class="eyebrow">untitled://</div><h1>${title}</h1></div><div class="muted">small browser, questionable decisions.</div></div>${body}`;}
async function renderNewtab(){shell('New Tab',`<section class="card"><div class="eyebrow">UNTITLED</div><h1 style="font-size:46px;margin-bottom:8px">Search / wander.</h1><p class="muted">A local Chromium shell with tabs, extensions, privacy controls and a few anime-related mistakes.</p><input class="input" id="search" placeholder="Search or enter address" autofocus></section><div class="grid" style="margin-top:12px">${card('Quick links',`<div class="grid"><button class="button" data-route="history">History</button><button class="button" data-route="downloads">Downloads</button><button class="button" data-route="bookmarks">Bookmarks</button><button class="button" data-route="settings">Settings</button></div>`)}${card('Tiny easter egg',`<p class="muted">The error pages know more about Matoi than they should.</p><button class="button" id="easter">Open error page</button>`)}</div>`);document.getElementById('search').onkeydown=e=>{if(e.key==='Enter')window.untitled.tabs.navigate(e.target.value)};document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>window.untitled.tabs.internal(b.dataset.route));document.getElementById('easter').onclick=()=>window.untitled.tabs.internal('error',{code:'404',url:'untitled://newtab'})}
async function renderHistory(){const items=await window.untitled.history.get();shell('History',`<div class="row"><div class="muted">${items.length} entries</div><button class="button danger" id="clear">Clear all</button></div><div class="list" id="list">${items.length?items.map(h=>`<div class="item"><div class="item-main"><div class="item-title">${esc(h.title)}</div><div class="item-url">${esc(h.url)}</div></div><span class="badge">${new Date(h.time).toLocaleString()}</span></div>`).join(''):'<p class="muted">Nothing here yet.</p>'}</div>`);document.getElementById('clear').onclick=async()=>{await window.untitled.history.clear();renderHistory()}}
async function renderDownloads(){const items=await window.untitled.downloads.get(); shell('Downloads',`<div class="list">${items.length?items.map(d=>`<div class="item"><div class="item-main"><div class="item-title">${esc(d.filename)}</div><div class="item-url">${esc(d.path)}</div></div><span class="badge">${esc(d.state)}</span>${d.path?`<button class="button show" data-p="${esc(d.path)}">folder</button>`:''}</div>`).join(''):'<p class="muted">No downloads in this session.</p>'}</div>`);document.querySelectorAll('.show').forEach(b=>b.onclick=()=>window.untitled.downloads.show(b.dataset.p))}
async function renderBookmarks(){const items=await window.untitled.bookmarks.get();shell('Bookmarks',`<div class="list">${items.length?items.map(b=>`<div class="item"><div class="item-main"><div class="item-title">${esc(b.title)}</div><div class="item-url">${esc(b.url)}</div></div><button class="button open" data-u="${esc(b.url)}">open</button><button class="button danger del" data-id="${b.id}">×</button></div>`).join(''):'<p class="muted">No bookmarks yet.</p>'}</div>`);document.querySelectorAll('.open').forEach(b=>b.onclick=()=>window.untitled.tabs.navigate(b.dataset.u));document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{await window.untitled.bookmarks.delete(b.dataset.id);renderBookmarks()})}
async function renderExtensions(){const items=await window.untitled.extensions.list();shell('Extensions',`<div class="row"><div><div class="label">Developer mode</div><div class="sub">Load unpacked Chromium extensions locally.</div></div><button class="button" id="load">Load unpacked</button></div><div class="list" style="margin-top:12px">${items.length?items.map(e=>`<div class="item"><div class="item-main"><div class="item-title">${esc(e.name)} <span class="badge">${esc(e.version)}</span></div><div class="item-url mono">${esc(e.id)}</div></div><button class="button danger remove" data-id="${esc(e.id)}">Remove</button></div>`).join(''):'<p class="muted">No extensions installed.</p>'}</div>`);document.getElementById('load').onclick=async()=>{const path=prompt('Enter the full path to an unpacked extension folder:');if(path){try{await window.untitled.extensions.load(path);renderExtensions()}catch(e){alert(e.message)}}};document.querySelectorAll('.remove').forEach(b=>b.onclick=async()=>{await window.untitled.extensions.remove(b.dataset.id);renderExtensions()})}
async function renderSettings(){
  const s=await window.untitled.settings.get();
  const rpcStatus=await window.untitled.discord.status();
  const statusText=(st)=>({CONNECTED:'Connected',CONNECTING:'Connecting…',RECONNECTING:'Reconnecting…',DISCONNECTED:'Disconnected',DISCORD_NOT_RUNNING:'Discord not running',INVALID_CLIENT_ID:'Invalid Application ID',ERROR:'Error'})[st]||st||'Disconnected';
  const statusClass=(st)=>st==='CONNECTED'?'good':st==='INVALID_CLIENT_ID'||st==='ERROR'?'bad':'';
  shell('Settings',`${card('General',`<div class="row"><div><div class="label">Home page</div><div class="sub">Opened by the home button and new tabs.</div></div><input class="input" style="max-width:360px" id="home" value="${esc(s.homePage)}"></div><div class="row"><div><div class="label">Search engine</div><div class="sub">Used for address bar searches.</div></div><select class="select" id="searchEngine" style="max-width:360px"><option value="https://duckduckgo.com/?q=">DuckDuckGo</option><option value="https://www.google.com/search?q=">Google</option><option value="https://www.bing.com/search?q=">Bing</option><option value="https://search.brave.com/search?q=">Brave Search</option><option value="https://www.startpage.com/sp/search?query=">Startpage</option></select></div><div class="row"><div><div class="label">Ask where to save downloads</div></div><input type="checkbox" id="askDownloads" ${s.askDownloadLocation?'checked':''}></div>`)}${card('Privacy',`<div class="row"><div><div class="label">Do Not Track</div></div><input type="checkbox" id="dnt" ${s.doNotTrack?'checked':''}></div><div class="row"><div><div class="label">Clear browsing data on exit</div></div><input type="checkbox" id="clearExit" ${s.clearDataOnExit?'checked':''}></div><div class="row"><button class="button danger" id="clearData">Clear cookies, cache & site data</button></div>`)}${card('Discord Rich Presence',`<div class="row"><div><div class="label">Enable Discord RPC</div><div class="sub">Uses Discord Desktop IPC. No Discord account data is stored by the browser.</div></div><input type="checkbox" id="rpcEnabled" ${s.discord?.enabled?'checked':''}></div><div class="row"><div class="label">Application ID</div><input class="input" id="rpcId" autocomplete="off" spellcheck="false" value="${esc(s.discord?.applicationId||'')}"></div><div class="row"><div class="label">Details</div><input class="input" id="rpcDetails" value="${esc(s.discord?.details||'Browsing the web')}"></div><div class="row"><div><div class="label">Show current domain</div></div><input type="checkbox" id="rpcSite" ${s.discord?.showSite!==false?'checked':''}></div><div class="row"><div><div class="label">Status</div><div class="sub" id="rpcStatus">● ${esc(statusText(rpcStatus.state))}</div><div class="sub mono" id="rpcError">${esc(rpcStatus.lastError||'')}</div></div><button class="button" id="rpcTest">Test Connection</button></div>`)}${card('Advanced',`<div class="row"><div><div class="label">Custom User-Agent</div><div class="sub">Only used if you choose custom.</div></div><input class="input" id="ua" value="${esc(s.userAgent?.custom||'')}"></div><div class="row"><button class="button" id="save">Save settings</button><span class="muted" id="saved"></span></div>`)} `);
  $('#searchEngine').value=s.searchEngine;
  const renderRpc=(st)=>{const el=$('#rpcStatus');const err=$('#rpcError');if(el)el.textContent=`● ${statusText(st.state)}`;if(err)err.textContent=st.lastError||'';};
  const off=window.untitled.discord.onStatus(renderRpc);
  $('#rpcTest').onclick=async()=>{
    const id=$('#rpcId').value.trim();
    $('#rpcStatus').textContent='● Connecting…';
    $('#rpcError').textContent='';
    const current=await window.untitled.settings.get();
    const next={...current,discord:{...current.discord,enabled:true,applicationId:id,details:$('#rpcDetails').value,showSite:$('#rpcSite').checked}};
    await window.untitled.settings.set(next);
    const result=await window.untitled.discord.test(id);
    renderRpc(result.status||{state:result.ok?'CONNECTED':'ERROR',lastError:result.error||''});
    if(result.ok) $('#saved').textContent='Discord RPC connected.'; else $('#saved').textContent=result.error||'Connection failed.';
    setTimeout(()=>$('#saved').textContent='',3500);
  };
  $('#save').onclick=async()=>{const next={homePage:$('#home').value||'untitled://newtab',searchEngine:$('#searchEngine').value,askDownloadLocation:$('#askDownloads').checked,doNotTrack:$('#dnt').checked,clearDataOnExit:$('#clearExit').checked,discord:{enabled:$('#rpcEnabled').checked,applicationId:$('#rpcId').value.trim(),details:$('#rpcDetails').value,showSite:$('#rpcSite').checked,showTitle:$('#rpcTitle').checked,showPageButton:$('#rpcPageButton').checked},userAgent:{...s.userAgent,mode:$('#ua').value?'custom':'default',custom:$('#ua').value}};await window.untitled.settings.set(next);document.getElementById('saved').textContent='Saved.';setTimeout(()=>document.getElementById('saved').textContent='',1500)};
  document.getElementById('clearData').onclick=async()=>{await window.untitled.privacy.clear({});alert('Browsing data cleared from the default profile.')};
}
async function renderAbout(){const v=await window.untitled.app.version();shell('About Untitled Browser',`${card('Untitled Browser',`<p class="muted">Small open-source Chromium browser for people who like settings, tabs and questionable UI decisions.</p><div class="grid"><div><div class="label">App</div><div class="sub mono">${esc(v.app)}</div></div><div><div class="label">Electron</div><div class="sub mono">${esc(v.electron)}</div></div><div><div class="label">Chromium</div><div class="sub mono">${esc(v.chromium)}</div></div><div><div class="label">Node</div><div class="sub mono">${esc(v.node)}</div></div></div>`)}${card('Links',`<div class="grid"><button class="button" id="github">Source code</button><button class="button" id="issues">Issues</button><button class="button" id="privacy">Privacy</button></div>`)}${card('Matoi easter egg',`<p class="muted">The attached image is stored locally and used only on custom error pages.</p><button class="button" id="err">Show error page</button>`)}`);document.getElementById('github').onclick=()=>window.untitled.shell.external('https://github.com/');document.getElementById('issues').onclick=()=>window.untitled.shell.external('https://github.com/');document.getElementById('privacy').onclick=()=>window.untitled.tabs.internal('privacy');document.getElementById('err').onclick=()=>window.untitled.tabs.internal('error',{code:'403',url:'about'})}
async function renderPrivacy(){shell('Privacy',`${card('Local data',`<p class="muted">Untitled Browser does not require an account. Browser profile data is kept in the local Electron userData directory. The browser does not implement hidden telemetry.</p><button class="button danger" id="clear">Clear storage</button>`)}${card('Important note',`<p class="muted">Privacy features reduce local tracking exposure but do not make you anonymous on the Internet. Websites, network providers, proxies and operating-system services may still observe activity.</p>`)}`);document.getElementById('clear').onclick=async()=>{await window.untitled.privacy.clear({});alert('Default profile storage cleared.')}}
async function renderTaskManager(){const m=await window.untitled.metrics.get();shell('Task Manager',`${card('Processes',`<div class="list">${m.map(x=>`<div class="item"><div class="item-main"><div class="item-title">${esc(x.name||x.type)}</div><div class="item-url mono">PID ${x.pid} · ${x.type}</div></div><span class="badge">CPU ${Number(x.cpu.percent||0).toFixed(1)}%</span><span class="badge">RAM ${Math.round((x.memory.workingSetSize||0)/1024)} MB</span></div>`).join('')}</div>`)}`)}
async function renderPerformance(){const m=await window.untitled.metrics.get();shell('Performance',`<div class="grid">${card('Processes',`<div class="code" style="font-size:34px">${m.length}</div><div class="sub">Electron / Chromium processes</div>`)}${card('RAM total',`<div class="code" style="font-size:34px">${Math.round(m.reduce((a,x)=>a+(x.memory.workingSetSize||0),0)/1024)} MB</div><div class="sub">Working set snapshot</div>`)}</div>`)}
async function renderShortcuts(){shell('Keyboard shortcuts',`<div class="card"><div class="list">${[['Ctrl+L','Focus address bar'],['Ctrl+T','New tab'],['Ctrl+W','Close tab'],['Ctrl+Shift+N','Private tab'],['Ctrl+Shift+T','Re-open / new tab'],['Ctrl+H','History'],['Ctrl+J','Downloads'],['Ctrl+D','Bookmark'],['Ctrl+F','Find in page (Chromium)'],['Ctrl+Shift+I','DevTools'],['F12','DevTools'],['Ctrl+Plus / Minus','Zoom'],['Ctrl+0','Reset zoom'],['Ctrl+Shift+S','Screenshot']].map(r=>`<div class="row"><span class="mono">${r[0]}</span><span class="muted">${r[1]}</span></div>`).join('')}</div></div>`) }
async function renderError(){
  const rawCode = params.get('code') || 'ERR_FAILED';
  const rawMessage = params.get('message') || 'Something went sideways.';
  const rawUrl = params.get('url') || '';
  const code = esc(rawCode);
  const message = esc(rawMessage);
  const url = esc(rawUrl);
  const friendly = {
    '403':'ACCESS DENIED', '404':'PAGE NOT FOUND', '500':'SERVER ERROR',
    '502':'BAD GATEWAY', '503':'SERVICE UNAVAILABLE', '504':'GATEWAY TIMEOUT'
  }[rawCode] || 'CONNECTION ERROR';
  app.innerHTML = `<section class="error-page">
    <div class="error-photo-wrap">
      <img class="error-photo" src="../../assets/matoi/error-main.png" alt="Matoi error illustration">
      <div class="sheet-overlay" aria-hidden="true">
        <div class="sheet-code">${code}</div>
        <div class="sheet-label">${esc(friendly)}</div>
      </div>
    </div>
    <div class="error-side">
      <div class="eyebrow">UNTITLED://ERROR</div>
      <h1>${code}</h1>
      <div class="error-title">${esc(friendly)}</div>
      <p class="muted">${rawCode.startsWith('ERR_') ? message : 'The page returned an HTTP error. You can retry it, go back, or open a fresh tab.'}</p>
      <div class="button-row">
        <button class="button" id="back">Back</button>
        <button class="button" id="retry">Retry</button>
        <button class="button primary" id="newTab">New tab</button>
      </div>
      <div class="small">${url}</div>
    </div>
  </section>`;
  document.getElementById('back').onclick=()=>window.untitled.tabs.action('error-back');
  document.getElementById('retry').onclick=()=>window.untitled.tabs.action('error-retry');
  document.getElementById('newTab').onclick=()=>window.untitled.tabs.action('error-new-tab');
}
async function boot(){ if(route==='newtab')return renderNewtab(); if(route==='history')return renderHistory(); if(route==='downloads')return renderDownloads(); if(route==='bookmarks')return renderBookmarks(); if(route==='extensions')return renderExtensions(); if(route==='settings')return renderSettings(); if(route==='about')return renderAbout(); if(route==='privacy')return renderPrivacy(); if(route==='task-manager')return renderTaskManager(); if(route==='performance')return renderPerformance(); if(route==='shortcuts')return renderShortcuts(); if(route==='error')return renderError(); return renderNewtab(); }
window.untitled?.onHistoryChanged(()=>{if(route==='history')renderHistory()});window.untitled?.downloads?.onChanged(()=>{if(route==='downloads')renderDownloads()});window.untitled?.bookmarks?.onChanged(()=>{if(route==='bookmarks')renderBookmarks()});boot();
